# Generated by Django 6.0.7 on 2026-07-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_void_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(help_text='UPI Virtual Payment Address (VPA), e.g. merchant@okicici', max_length=100)),
                ('upi_payee_name', models.CharField(help_text="Payee name that appears on the customer's UPI app", max_length=200)),
            ],
            options={
                'verbose_name': 'Store Configuration',
                'verbose_name_plural': 'Store Configuration',
            },
        ),
    ]
