# Generated by Django 6.0.7 on 2026-07-31 15:35

from django.db import migrations

def fix_legacy_payments(apps, schema_editor):
    Order = apps.get_model('core', 'Order')
    # For any completed order that has 0 amounts but a total > 0, assume it was Cash
    orders = Order.objects.filter(status='COMPLETED', cash_amount=0, upi_amount=0, card_amount=0, total_amount__gt=0)
    for order in orders:
        order.cash_amount = order.total_amount
        order.save(update_fields=['cash_amount'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_payment_method_order_card_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_legacy_payments),
    ]
